version: '3.9'

services:
  backend:
    image: cotbert2/e-commerce-back:v2
    container_name: ecommerce-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ecommerce_db
      - NODE_ENV=production
      - PORT=3000
    networks:
      - ecommerce-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_e_commerce
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce_db
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecommerce-network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  ecommerce-network:
    driver: bridge
